# Generated by Django 3.0.2 on 2020-05-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userprofile_image_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_1',
        ),
    ]
